# -*- coding: utf-8 -*-
"""5 min APPLE,NU,HONEYWELL,MICROSOFT .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spVXxwvm5b-N8RX8VE8wpiGrSGs69WXQ
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, kpss, coint
import matplotlib.pyplot as plt
from google.colab import files
import warnings
import os
import IPython.display as display

# Suppress statsmodels warnings
warnings.filterwarnings("ignore", category=UserWarning, message="Covariance matrix calculated using the outer product of gradients")

# Function to clean series (handle NaN/Inf)
def clean_series(series, name):
    try:
        print(f"Checking {name} for NaN/Inf values...")
        if not pd.api.types.is_numeric_dtype(series):
            raise ValueError(f"{name} contains non-numeric values.")
        if series.isna().any() or np.isinf(series).any():
            print(f"{name} contains NaN or Inf values. Cleaning...")
            series = series.fillna(method='ffill').fillna(method='bfill').dropna()
            series = series.replace([np.inf], series.max())
            series = series.replace([-np.inf], series.min())
        if series.isna().any():
            raise ValueError(f"{name} still contains NaN values after cleaning.")
        if len(series) == 0:
            raise ValueError(f"{name} is empty after cleaning.")
        print(f"{name} is clean with {len(series)} observations.")
        return series
    except Exception as e:
        raise ValueError(f"Failed to clean {name}: {str(e)}")

# Function to upload and read Excel files
def load_stock_data(max_retries=3):
    for attempt in range(max_retries):
        try:
            # Apple
            print("Upload APPLE 5 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Apple.")
            apple_filename = list(uploaded.keys())[0]
            if not apple_filename.endswith('.xlsx'):
                raise ValueError("Apple file must be an Excel (.xlsx) file.")
            apple_df = pd.read_excel(apple_filename)

            # Microsoft
            print("Upload MICROSOFT 5 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Microsoft.")
            msft_filename = list(uploaded.keys())[0]
            if not msft_filename.endswith('.xlsx'):
                raise ValueError("Microsoft file must be an Excel (.xlsx) file.")
            msft_df = pd.read_excel(msft_filename)

            # Honeywell
            print("Upload HONEYWELL 5 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Honeywell.")
            honeywell_filename = list(uploaded.keys())[0]
            if not honeywell_filename.endswith('.xlsx'):
                raise ValueError("Honeywell file must be an Excel (.xlsx) file.")
            honeywell_df = pd.read_excel(honeywell_filename)

            # NU
            print("Upload NU 5 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for NU.")
            nu_filename = list(uploaded.keys())[0]
            if not nu_filename.endswith('.xlsx'):
                raise ValueError("NU file must be an Excel (.xlsx) file.")
            nu_df = pd.read_excel(nu_filename)

            # Check for 'Close' column
            for df, name in [(apple_df, "Apple"), (msft_df, "Microsoft"), (honeywell_df, "Honeywell"), (nu_df, "NU")]:
                if 'Close' not in df.columns:
                    raise ValueError(f"{name} Excel file must contain a 'Close' column.")

            # Clean series
            apple_df['Close'] = clean_series(apple_df['Close'], "Apple Close")
            msft_df['Close'] = clean_series(msft_df['Close'], "Microsoft Close")
            honeywell_df['Close'] = clean_series(honeywell_df['Close'], "Honeywell Close")
            nu_df['Close'] = clean_series(nu_df['Close'], "NU Close")

            print(f"Apple data shape: {apple_df.shape}")
            print(f"Microsoft data shape: {msft_df.shape}")
            print(f"Honeywell data shape: {honeywell_df.shape}")
            print(f"NU data shape: {nu_df.shape}")
            return apple_df, msft_df, honeywell_df, nu_df
        except Exception as e:
            print(f"Error loading files (attempt {attempt + 1}/{max_retries}): {str(e)}")
            if attempt == max_retries - 1:
                raise ValueError("Failed to load Excel files after multiple attempts.")

# Function to ensure datetime index
def ensure_datetime_index(df, series, name):
    try:
        if not pd.api.types.is_datetime64_any_dtype(df.index):
            datetime_cols = ['Date', 'Timestamp', 'datetime', 'time']
            for col in datetime_cols:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors='coerce')
                    if df[col].isna().all():
                        raise ValueError(f"Invalid datetime values in {col} for {name}.")
                    df.set_index(col, inplace=True)
                    series.index = df.index
                    break
            else:
                print(f"Warning: No datetime column found for {name}. Using default index.")
                df.index = pd.RangeIndex(len(df))
                series.index = df.index
        return df, series
    except Exception as e:
        print(f"Warning: Failed to set datetime index for {name}: {str(e)}. Using default index.")
        df.index = pd.RangeIndex(len(df))
        series.index = df.index
        return df, series

# Function to perform stationarity tests
def stationarity_tests(series, name):
    try:
        print(f"\nStationarity Tests for {name}")
        series = clean_series(series, name)

        adf_result = adfuller(series, autolag='AIC')
        print(f"ADF Test p-value: {adf_result[1]:.4f}")
        kpss_result = kpss(series, regression='c')
        print(f"KPSS Test p-value: {kpss_result[1]:.4f}")

        plt.figure(figsize=(12, 6))
        plt.plot(series, label='Original Series', color='blue')
        plt.title(f'Original {name} Series')
        plt.xlabel('Time')
        plt.ylabel('Price')
        plt.grid(True)
        plt.legend()
        filename = f'{name}_original_series.png'
        plt.savefig(filename)
        plt.show()
        plt.close()
        print(f"Saved and displayed plot: {filename}")

        is_differenced = False
        diff_series = series
        if adf_result[1] > 0.05 or kpss_result[1] < 0.05:
            print(f"{name} is non-stationary. Differencing...")
            diff_series = series.diff().dropna()
            diff_series = clean_series(diff_series, f"Differenced {name}")
            plt.figure(figsize=(12, 6))
            plt.plot(diff_series, label='Differenced Series', color='orange')
            plt.title(f'Differenced {name} Series')
            plt.xlabel('Time')
            plt.ylabel('Price Difference')
            plt.grid(True)
            plt.legend()
            filename = f'{name}_differenced_series.png'
            plt.savefig(filename)
            plt.show()
            plt.close()
            print(f"Saved and displayed plot: {filename}")
            is_differenced = True
        return diff_series, is_differenced
    except Exception as e:
        print(f"Warning: Stationarity tests failed for {name}: {str(e)}. Using original series.")
        return series, False

# Function to perform cointegration test between pairs
def cointegration_test(series1, series2, name1, name2):
    try:
        print(f"\nCointegration Test between {name1} and {name2}")
        df = pd.DataFrame({name1: series1, name2: series2}).dropna()
        series1, series2 = df[name1], df[name2]
        if len(series1) < 2:
            raise ValueError("Insufficient data for cointegration test.")

        series1 = clean_series(series1, name1)
        series2 = clean_series(series2, name2)

        score, p_value, _ = coint(series1, series2)
        print(f"Engle-Granger Cointegration Test p-value: {p_value:.4f}")
        if p_value < 0.05:
            print("Series are cointegrated")
        else:
            print("Series are not cointegrated")

        plt.figure(figsize=(12, 6))
        plt.plot(series1, label=name1, color='blue')
        plt.plot(series2, label=name2, color='green')
        plt.title(f'{name1} vs {name2} for Cointegration')
        plt.xlabel('Time')
        plt.ylabel('Price')
        plt.grid(True)
        plt.legend()
        filename = f'{name1}_vs_{name2}_cointegration.png'
        plt.savefig(filename)
        plt.show()
        plt.close()
        print(f"Saved and displayed plot: {filename}")

        return series1, series2
    except Exception as e:
        print(f"Warning: Cointegration test failed: {str(e)}. Skipping.")
        return series1, series2

# Function to fit and forecast models
def fit_and_forecast(series, name, steps=10):
    try:
        print(f"\nFitting Models for {name}")
        series = clean_series(series.dropna(), name)
        if len(series) < 50:
            raise ValueError(f"Insufficient data for {name}: {len(series)} observations.")

        train_size = int(len(series) * 0.8)
        train, test = series[:train_size], series[train_size:]
        if len(test) < steps:
            print(f"Warning: Test set too small ({len(test)} < {steps}). Adjusting steps.")
            steps = len(test)

        ar_forecast = np.full(steps, np.nan)
        try:
            ar_model = AutoReg(train, lags=1).fit()
            ar_forecast = ar_model.forecast(steps=steps)
            print("AR Model Summary:")
            print(ar_model.summary())
        except Exception as e:
            print(f"Warning: AR model failed for {name}: {str(e)}")

        arma_forecast = np.full(steps, np.nan)
        try:
            arma_model = ARIMA(train, order=(1, 0, 1)).fit()
            arma_forecast = arma_model.forecast(steps=steps)
            print("ARMA Model Summary:")
            print(arma_model.summary())
        except Exception as e:
            print(f"Warning: ARMA model failed for {name}: {str(e)}")

        arima_forecast = np.full(steps, np.nan)
        try:
            arima_model = ARIMA(train, order=(1, 1, 1)).fit()
            arima_forecast = arima_model.forecast(steps=steps)
            print("ARIMA Model Summary:")
            print(arima_model.summary())
        except Exception as e:
            print(f"Warning: ARIMA model failed for {name}: {str(e)}")

        return train, test, ar_forecast, arma_forecast, arima_forecast, steps
    except Exception as e:
        print(f"Warning: Forecasting failed for {name}: {str(e)}")
        return None, None, np.full(steps, np.nan), np.full(steps, np.nan), np.full(steps, np.nan), steps

# Function to create combined graph for all stocks
def plot_combined_graph(stocks_data):
    try:
        print("Generating combined graph...")
        fig, axes = plt.subplots(4, 2, figsize=(18, 16), gridspec_kw={'height_ratios': [1, 1, 1, 1.5]})
        fig.suptitle('Time Series Analysis: Apple, Microsoft, Honeywell, and NU Close Prices', fontsize=16, y=1.02)

        stock_names = ['Apple', 'Microsoft', 'Honeywell', 'NU']
        colors = ['blue', 'green', 'purple', 'orange']

        for idx, (name, data) in enumerate(stocks_data.items()):
            series, diff_series, is_diff, train, test, ar_forecast, arma_forecast, arima_forecast, steps = data

            # Stationarity Plot
            if len(series) > 0:
                axes[idx, 0].plot(series, label='Original', color=colors[idx])
                if is_diff and len(diff_series) > 0:
                    axes[idx, 0].plot(diff_series, label='Differenced', color=colors[idx], alpha=0.5)
                axes[idx, 0].set_title(f'{name} Close: Stationarity')
                axes[idx, 0].set_xlabel('Time')
                axes[idx, 0].set_ylabel('Price / Diff')
                axes[idx, 0].grid(True)
                axes[idx, 0].legend()
            else:
                axes[idx, 0].text(0.5, 0.5, f'No {name} data', ha='center', va='center')

            # Forecast Plot
            if train is not None and len(train) > 0:
                axes[idx, 1].plot(train.index[-50:], train[-50:], label='Train', color=colors[idx])
                axes[idx, 1].plot(test.index[:steps], test[:steps], label='Test', color='black')
                if not np.isnan(ar_forecast).all():
                    axes[idx, 1].plot(test.index[:steps], ar_forecast, label='AR', color='red')
                if not np.isnan(arma_forecast).all():
                    axes[idx, 1].plot(test.index[:steps], arma_forecast, label='ARMA', color='green')
                if not np.isnan(arima_forecast).all():
                    axes[idx, 1].plot(test.index[:steps], arima_forecast, label='ARIMA', color='purple')
                rolling_mean = train.rolling(window=10).mean()
                axes[idx, 1].plot(train.index[-50:], rolling_mean[-50:], label='10-Period Mean', color='orange', linestyle='--')
                axes[idx, 1].set_title(f'{name} Close: Forecasts')
                axes[idx, 1].set_xlabel('Time')
                axes[idx, 1].set_ylabel('Price')
                axes[idx, 1].grid(True)
                axes[idx, 1].legend()
            else:
                axes[idx, 1].text(0.5, 0.5, f'No {name} forecast data', ha='center', va='center')

        plt.tight_layout(rect=[0, 0, 1, 0.95])
        filename = 'combined_analysis.png'
        plt.savefig(filename, dpi=300, bbox_inches='tight')
        plt.show()
        plt.close()
        print(f"Saved and displayed combined graph: {filename}")
        display.display(display.Image(filename))
    except Exception as e:
        print(f"Warning: Failed to create combined graph: {str(e)}")

# Function to plot individual forecasts
def plot_individual_forecasts(train, test, ar_forecast, arma_forecast, arima_forecast, name, steps=10):
    try:
        models = {'AR': ar_forecast, 'ARMA': arma_forecast, 'ARIMA': arima_forecast}
        for model_name, forecast in models.items():
            if len(forecast) != steps or np.isnan(forecast).all():
                print(f"Warning: Invalid {model_name} forecast for {name}. Skipping plot.")
                continue
            plt.figure(figsize=(12, 6))
            plt.plot(train.index[-50:], train[-50:], label='Train', color='blue')
            plt.plot(test.index[:steps], test[:steps], label='Test', color='black')
            plt.plot(test.index[:steps], forecast, label=f'{model_name} Forecast', color='red')
            plt.title(f'{model_name} Forecasting for {name}')
            plt.xlabel('Time')
            plt.ylabel('Price')
            plt.grid(True)
            plt.legend()
            filename = f'{name}_{model_name}_forecast.png'
            plt.savefig(filename)
            plt.show()
            plt.close()
            print(f"Saved and displayed plot: {filename}")
            display.display(display.Image(filename))
    except Exception as e:
        print(f"Warning: Failed to plot individual forecasts for {name}: {str(e)}")

# Main execution
def main():
    try:
        # Load data
        apple_df, msft_df, honeywell_df, nu_df = load_stock_data()
        apple_close = apple_df['Close']
        msft_close = msft_df['Close']
        honeywell_close = honeywell_df['Close']
        nu_close = nu_df['Close']

        # Ensure datetime indices
        apple_df, apple_close = ensure_datetime_index(apple_df, apple_close, "Apple Close")
        msft_df, msft_close = ensure_datetime_index(msft_df, msft_close, "Microsoft Close")
        honeywell_df, honeywell_close = ensure_datetime_index(honeywell_df, honeywell_close, "Honeywell Close")
        nu_df, nu_close = ensure_datetime_index(nu_df, nu_close, "NU Close")

        # Stationarity tests
        apple_series, apple_is_diff = stationarity_tests(apple_close, "Apple Close")
        msft_series, msft_is_diff = stationarity_tests(msft_close, "Microsoft Close")
        honeywell_series, honeywell_is_diff = stationarity_tests(honeywell_close, "Honeywell Close")
        nu_series, nu_is_diff = stationarity_tests(nu_close, "NU Close")

        # Cointegration tests for pairs
        pairs = [
            (apple_series, msft_series, "Apple Close", "Microsoft Close"),
            (apple_series, honeywell_series, "Apple Close", "Honeywell Close"),
            (apple_series, nu_series, "Apple Close", "NU Close"),
            (msft_series, honeywell_series, "Microsoft Close", "Honeywell Close"),
            (msft_series, nu_series, "Microsoft Close", "NU Close"),
            (honeywell_series, nu_series, "Honeywell Close", "NU Close")
        ]
        for series1, series2, name1, name2 in pairs:
            series1, series2 = cointegration_test(series1, series2, name1, name2)

        # Fit models and forecast
        apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps = fit_and_forecast(apple_series, "Apple Close")
        msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps = fit_and_forecast(msft_series, "Microsoft Close")
        honeywell_train, honeywell_test, honeywell_ar, honeywell_arma, honeywell_arima, honeywell_steps = fit_and_forecast(honeywell_series, "Honeywell Close")
        nu_train, nu_test, nu_ar, nu_arma, nu_arima, nu_steps = fit_and_forecast(nu_series, "NU Close")

        # Individual forecast plots
        for name, train, test, ar, arma, arima, steps in [
            ("Apple Close", apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps),
            ("Microsoft Close", msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps),
            ("Honeywell Close", honeywell_train, honeywell_test, honeywell_ar, honeywell_arma, honeywell_arima, honeywell_steps),
            ("NU Close", nu_train, nu_test, nu_ar, nu_arma, nu_arima, nu_steps)
        ]:
            if train is not None and len(train) > 0:
                plot_individual_forecasts(train, test, ar, arma, arima, name, steps)

        # Combined graph
        stocks_data = {
            'Apple': (apple_close, apple_series if apple_is_diff else None, apple_is_diff, apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps),
            'Microsoft': (msft_close, msft_series if msft_is_diff else None, msft_is_diff, msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps),
            'Honeywell': (honeywell_close, honeywell_series if honeywell_is_diff else None, honeywell_is_diff, honeywell_train, honeywell_test, honeywell_ar, honeywell_arma, honeywell_arima, honeywell_steps),
            'NU': (nu_close, nu_series if nu_is_diff else None, nu_is_diff, nu_train, nu_test, nu_ar, nu_arma, nu_arima, nu_steps)
        }
        if any(len(data[0]) > 0 for data in stocks_data.values()):
            plot_combined_graph(stocks_data)

        # List and download saved plots
        print("\nSaved Plots:")
        saved_files = [f for f in os.listdir() if f.endswith('.png')]
        for f in saved_files:
            print(f"- {f}")
            files.download(f)
        if not saved_files:
            print("No plots were saved.")
    except Exception as e:
        print(f"Error in main execution: {str(e)}")

if __name__ == "__main__":
    main()