# -*- coding: utf-8 -*-
"""APPLE vs Microsoft 1 min

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fSzSTqn4ijUkOGyg4xYEeu6FJH0j_YDU
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, kpss, coint
import matplotlib.pyplot as plt
from google.colab import files
import warnings
import uuid
import os
from datetime import datetime

warnings.filterwarnings("ignore")

# Function to clean series (handle NaN/Inf)
def clean_series(series, name):
    try:
        print(f"Checking {name} for NaN/Inf values...")
        if not pd.api.types.is_numeric_dtype(series):
            raise ValueError(f"{name} contains non-numeric values.")
        if series.isna().any() or np.isinf(series).any():
            print(f"{name} contains NaN or Inf values. Cleaning...")
            # Forward fill NaNs
            series = series.fillna(method='ffill')
            # Backward fill remaining NaNs
            series = series.fillna(method='bfill')
            # Drop any remaining NaNs
            series = series.dropna()
            # Replace Inf with max/min valid value
            series = series.replace([np.inf], series.max())
            series = series.replace([-np.inf], series.min())
        if series.isna().any():
            raise ValueError(f"{name} still contains NaN values after cleaning.")
        if len(series) == 0:
            raise ValueError(f"{name} is empty after cleaning.")
        print(f"{name} is clean with {len(series)} observations.")
        return series
    except Exception as e:
        raise ValueError(f"Failed to clean {name}: {str(e)}")

# Function to upload and read Excel files with retry
def load_stock_data(max_retries=3):
    for attempt in range(max_retries):
        try:
            print("Upload APPLE 1 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Apple.")
            apple_filename = list(uploaded.keys())[0]
            if not apple_filename.endswith('.xlsx'):
                raise ValueError("Apple file must be an Excel (.xlsx) file.")
            apple_df = pd.read_excel(apple_filename)

            print("Upload MICROSOFT 1 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Microsoft.")
            msft_filename = list(uploaded.keys())[0]
            if not msft_filename.endswith('.xlsx'):
                raise ValueError("Microsoft file must be an Excel (.xlsx) file.")
            msft_df = pd.read_excel(msft_filename)

            # Validate 'Close' column
            if 'Close' not in apple_df.columns or 'Close' not in msft_df.columns:
                raise ValueError("Excel files must contain a 'Close' column.")

            # Clean 'Close' columns
            apple_df['Close'] = clean_series(apple_df['Close'], "Apple Close")
            msft_df['Close'] = clean_series(msft_df['Close'], "Microsoft Close")

            return apple_df, msft_df
        except Exception as e:
            print(f"Error loading files (attempt {attempt + 1}/{max_retries}): {str(e)}")
            if attempt == max_retries - 1:
                raise ValueError("Failed to load Excel files after multiple attempts.")
            print("Retrying...")

# Function to ensure datetime index
def ensure_datetime_index(df, series, name):
    try:
        if not pd.api.types.is_datetime64_any_dtype(df.index):
            # Try common datetime column names
            datetime_cols = ['Date', 'Timestamp', 'datetime', 'time']
            for col in datetime_cols:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors='coerce')
                    if df[col].isna().all():
                        raise ValueError(f"Invalid datetime values in {col} for {name}.")
                    df.set_index(col, inplace=True)
                    series.index = df.index
                    break
            else:
                print(f"Warning: No datetime column found for {name}. Using default index.")
                df.index = pd.RangeIndex(len(df))
                series.index = df.index
        return df, series
    except Exception as e:
        print(f"Warning: Failed to set datetime index for {name}: {str(e)}. Using default index.")
        df.index = pd.RangeIndex(len(df))
        series.index = df.index
        return df, series

# Function to perform stationarity tests and plot series
def stationarity_tests(series, name):
    try:
        print(f"\nStationarity Tests for {name}")
        series = clean_series(series, name)

        # ADF Test
        adf_result = adfuller(series, autolag='AIC')
        print(f"ADF Test p-value: {adf_result[1]:.4f}")
        # KPSS Test
        kpss_result = kpss(series, regression='c')
        print(f"KPSS Test p-value: {kpss_result[1]:.4f}")

        # Plot original series
        plt.figure(figsize=(12, 6))
        plt.plot(series, label='Original Series')
        plt.title(f'Original {name} Series')
        plt.legend()
        plt.savefig(f'{name}_original_series.png')
        plt.close()

        # Check stationarity and difference if needed
        if adf_result[1] > 0.05 or kpss_result[1] < 0.05:
            print(f"{name} is non-stationary. Differencing...")
            diff_series = series.diff().dropna()
            diff_series = clean_series(diff_series, f"Differenced {name}")
            # Plot differenced series
            plt.figure(figsize=(12, 6))
            plt.plot(diff_series, label='Differenced Series')
            plt.title(f'Differenced {name} Series')
            plt.legend()
            plt.savefig(f'{name}_differenced_series.png')
            plt.close()
            return diff_series
        return series
    except Exception as e:
        raise ValueError(f"Stationarity tests failed for {name}: {str(e)}")

# Function to perform cointegration test and plot series
def cointegration_test(series1, series2, name1, name2):
    try:
        print(f"\nCointegration Test between {name1} and {name2}")
        # Align series by common index
        df = pd.DataFrame({name1: series1, name2: series2}).dropna()
        series1, series2 = df[name1], df[name2]
        if len(series1) < 2:
            raise ValueError("Insufficient data for cointegration test after alignment.")

        series1 = clean_series(series1, name1)
        series2 = clean_series(series2, name2)

        score, p_value, _ = coint(series1, series2)
        print(f"Engle-Granger Cointegration Test p-value: {p_value:.4f}")
        if p_value < 0.05:
            print("Series are cointegrated")
        else:
            print("Series are not cointegrated")

        # Plot both series
        plt.figure(figsize=(12, 6))
        plt.plot(series1, label=name1)
        plt.plot(series2, label=name2)
        plt.title(f'{name1} vs {name2} for Cointegration')
        plt.legend()
        plt.savefig(f'{name1}_vs_{name2}_cointegration.png')
        plt.close()
    except Exception as e:
        print(f"Warning: Cointegration test failed: {str(e)}. Skipping.")

# Function to plot individual model forecasts
def plot_individual_forecasts(train, test, ar_forecast, arma_forecast, arima_forecast, name, steps=10):
    try:
        models = {'AR': ar_forecast, 'ARMA': arma_forecast, 'ARIMA': arima_forecast}
        for model_name, forecast in models.items():
            if len(forecast) != steps:
                print(f"Warning: {model_name} forecast length mismatch for {name}. Skipping plot.")
                continue
            plt.figure(figsize=(12, 6))
            plt.plot(train.index[-50:], train[-50:], label='Train')
            plt.plot(test.index[:steps], test[:steps], label='Test')
            plt.plot(test.index[:steps], forecast, label=f'{model_name} Forecast')
            plt.title(f'{model_name} Forecasting for {name}')
            plt.legend()
            filename = f'{name}_{model_name}_forecast.png'
            plt.savefig(filename)
            plt.close()
            print(f"Saved plot: {filename}")
    except Exception as e:
        print(f"Warning: Failed to plot individual forecasts for {name}: {str(e)}")

# Function to plot combined forecast with trend
def plot_with_trend(train, test, ar_forecast, arma_forecast, arima_forecast, name, steps=10):
    try:
        plt.figure(figsize=(12, 6))
        plt.plot(train.index[-50:], train[-50:], label='Train')
        plt.plot(test.index[:steps], test[:steps], label='Test')
        plt.plot(test.index[:steps], ar_forecast, label='AR Forecast')
        plt.plot(test.index[:steps], arma_forecast, label='ARMA Forecast')
        plt.plot(test.index[:steps], arima_forecast, label='ARIMA Forecast')
        # Add rolling mean for trend
        rolling_mean = train.rolling(window=10).mean()
        plt.plot(train.index[-50:], rolling_mean[-50:], label='10-Period Rolling Mean', linestyle='--')
        plt.title(f'Forecasting with Trend for {name}')
        plt.legend()
        filename = f'{name}_forecast_with_trend.png'
        plt.savefig(filename)
        plt.close()
        print(f"Saved plot: {filename}")
    except Exception as e:
        print(f"Warning: Failed to plot forecast with trend for {name}: {str(e)}")

# Function to fit and forecast models
def fit_and_forecast(series, name, steps=10):
    try:
        print(f"\nFitting Models for {name}")
        series = clean_series(series.dropna(), name)
        if len(series) < 50:
            raise ValueError(f"Insufficient data for {name}: {len(series)} observations.")

        train_size = int(len(series) * 0.8)
        train, test = series[:train_size], series[train_size:]
        if len(test) < steps:
            print(f"Warning: Test set too small ({len(test)} < {steps}). Adjusting steps.")
            steps = len(test)

        # AR Model
        try:
            ar_model = AutoReg(train, lags=1).fit()
            ar_forecast = ar_model.forecast(steps=steps)
            print("AR Model Summary:")
            print(ar_model.summary())
        except Exception as e:
            print(f"Warning: AR model failed for {name}: {str(e)}")
            ar_forecast = np.full(steps, np.nan)

        # ARMA Model (using ARIMA with d=0, p=1, q=1)
        try:
            arma_model = ARIMA(train, order=(1, 0, 1)).fit()
            arma_forecast = arma_model.forecast(steps=steps)
            print("ARMA Model Summary:")
            print(arma_model.summary())
        except Exception as e:
            print(f"Warning: ARMA model failed for {name}: {str(e)}")
            arma_forecast = np.full(steps, np.nan)

        # ARIMA Model (p=1, d=1, q=1)
        try:
            arima_model = ARIMA(train, order=(1, 1, 1)).fit()
            arima_forecast = arima_model.forecast(steps=steps)
            print("ARIMA Model Summary:")
            print(arima_model.summary())
        except Exception as e:
            print(f"Warning: ARIMA model failed for {name}: {str(e)}")
            arima_forecast = np.full(steps, np.nan)

        # Plot forecasts
        plot_individual_forecasts(train, test, ar_forecast, arma_forecast, arima_forecast, name, steps)
        plot_with_trend(train, test, ar_forecast, arma_forecast, arima_forecast, name, steps)
    except Exception as e:
        print(f"Warning: Forecasting failed for {name}: {str(e)}")

# Main execution
def main():
    try:
        # Load data
        apple_df, msft_df = load_stock_data()

        # Extract closing prices
        apple_close = apple_df['Close']
        msft_close = msft_df['Close']

        # Ensure datetime indices
        apple_df, apple_close = ensure_datetime_index(apple_df, apple_close, "Apple Close")
        msft_df, msft_close = ensure_datetime_index(msft_df, msft_close, "Microsoft Close")

        # Stationarity tests
        apple_close = stationarity_tests(apple_close, "Apple Close")
        msft_close = stationarity_tests(msft_close, "Microsoft Close")

        # Cointegration test
        cointegration_test(apple_close, msft_close, "Apple Close", "Microsoft Close")

        # Fit models and forecast
        fit_and_forecast(apple_close, "Apple Close")
        fit_and_forecast(msft_close, "Microsoft Close")

        # List saved plots
        print("\nSaved Plots:")
        saved_files = [f for f in os.listdir() if f.endswith('.png')]
        for f in saved_files:
            print(f"- {f}")
        if not saved_files:
            print("No plots were saved.")
    except Exception as e:
        print(f"Error in main execution: {str(e)}")

if __name__ == "__main__":
    main()

import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, kpss, coint
import matplotlib.pyplot as plt
from google.colab import files
import warnings
import os

warnings.filterwarnings("ignore")

# Function to clean series (handle NaN/Inf)
def clean_series(series, name):
    try:
        print(f"Checking {name} for NaN/Inf values...")
        if not pd.api.types.is_numeric_dtype(series):
            raise ValueError(f"{name} contains non-numeric values.")
        if series.isna().any() or np.isinf(series).any():
            print(f"{name} contains NaN or Inf values. Cleaning...")
            series = series.fillna(method='ffill').fillna(method='bfill').dropna()
            series = series.replace([np.inf], series.max())
            series = series.replace([-np.inf], series.min())
        if series.isna().any():
            raise ValueError(f"{name} still contains NaN values after cleaning.")
        if len(series) == 0:
            raise ValueError(f"{name} is empty after cleaning.")
        print(f"{name} is clean with {len(series)} observations.")
        return series
    except Exception as e:
        raise ValueError(f"Failed to clean {name}: {str(e)}")

# Function to upload and read Excel files
def load_stock_data(max_retries=3):
    for attempt in range(max_retries):
        try:
            print("Upload APPLE 1 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Apple.")
            apple_filename = list(uploaded.keys())[0]
            if not apple_filename.endswith('.xlsx'):
                raise ValueError("Apple file must be an Excel (.xlsx) file.")
            apple_df = pd.read_excel(apple_filename)

            print("Upload MICROSOFT 1 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Microsoft.")
            msft_filename = list(uploaded.keys())[0]
            if not msft_filename.endswith('.xlsx'):
                raise ValueError("Microsoft file must be an Excel (.xlsx) file.")
            msft_df = pd.read_excel(msft_filename)

            if 'Close' not in apple_df.columns or 'Close' not in msft_df.columns:
                raise ValueError("Excel files must contain a 'Close' column.")

            apple_df['Close'] = clean_series(apple_df['Close'], "Apple Close")
            msft_df['Close'] = clean_series(msft_df['Close'], "Microsoft Close")

            return apple_df, msft_df
        except Exception as e:
            print(f"Error loading files (attempt {attempt + 1}/{max_retries}): {str(e)}")
            if attempt == max_retries - 1:
                raise ValueError("Failed to load Excel files after multiple attempts.")

# Function to ensure datetime index
def ensure_datetime_index(df, series, name):
    try:
        if not pd.api.types.is_datetime64_any_dtype(df.index):
            datetime_cols = ['Date', 'Timestamp', 'datetime', 'time']
            for col in datetime_cols:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors='coerce')
                    if df[col].isna().all():
                        raise ValueError(f"Invalid datetime values in {col} for {name}.")
                    df.set_index(col, inplace=True)
                    series.index = df.index
                    break
            else:
                print(f"Warning: No datetime column found for {name}. Using default index.")
                df.index = pd.RangeIndex(len(df))
                series.index = df.index
        return df, series
    except Exception as e:
        print(f"Warning: Failed to set datetime index for {name}: {str(e)}. Using default index.")
        df.index = pd.RangeIndex(len(df))
        series.index = df.index
        return df, series

# Function to perform stationarity tests and return differenced series
def stationarity_tests(series, name):
    try:
        print(f"\nStationarity Tests for {name}")
        series = clean_series(series, name)

        adf_result = adfuller(series, autolag='AIC')
        print(f"ADF Test p-value: {adf_result[1]:.4f}")
        kpss_result = kpss(series, regression='c')
        print(f"KPSS Test p-value: {kpss_result[1]:.4f}")

        plt.figure(figsize=(12, 6))
        plt.plot(series, label='Original Series')
        plt.title(f'Original {name} Series')
        plt.legend()
        plt.savefig(f'{name}_original_series.png')
        plt.close()

        is_differenced = False
        diff_series = series
        if adf_result[1] > 0.05 or kpss_result[1] < 0.05:
            print(f"{name} is non-stationary. Differencing...")
            diff_series = series.diff().dropna()
            diff_series = clean_series(diff_series, f"Differenced {name}")
            plt.figure(figsize=(12, 6))
            plt.plot(diff_series, label='Differenced Series')
            plt.title(f'Differenced {name} Series')
            plt.legend()
            plt.savefig(f'{name}_differenced_series.png')
            plt.close()
            is_differenced = True
        return diff_series, is_differenced
    except Exception as e:
        print(f"Warning: Stationarity tests failed for {name}: {str(e)}. Using original series.")
        return series, False

# Function to perform cointegration test
def cointegration_test(series1, series2, name1, name2):
    try:
        print(f"\nCointegration Test between {name1} and {name2}")
        df = pd.DataFrame({name1: series1, name2: series2}).dropna()
        series1, series2 = df[name1], df[name2]
        if len(series1) < 2:
            raise ValueError("Insufficient data for cointegration test.")

        series1 = clean_series(series1, name1)
        series2 = clean_series(series2, name2)

        score, p_value, _ = coint(series1, series2)
        print(f"Engle-Granger Cointegration Test p-value: {p_value:.4f}")
        if p_value < 0.05:
            print("Series are cointegrated")
        else:
            print("Series are not cointegrated")

        plt.figure(figsize=(12, 6))
        plt.plot(series1, label=name1)
        plt.plot(series2, label=name2)
        plt.title(f'{name1} vs {name2} for Cointegration')
        plt.legend()
        plt.savefig(f'{name1}_vs_{name2}_cointegration.png')
        plt.close()

        return series1, series2
    except Exception as e:
        print(f"Warning: Cointegration test failed: {str(e)}. Skipping.")
        return series1, series2

# Function to fit and forecast models
def fit_and_forecast(series, name, steps=10):
    try:
        print(f"\nFitting Models for {name}")
        series = clean_series(series.dropna(), name)
        if len(series) < 50:
            raise ValueError(f"Insufficient data for {name}: {len(series)} observations.")

        train_size = int(len(series) * 0.8)
        train, test = series[:train_size], series[train_size:]
        if len(test) < steps:
            print(f"Warning: Test set too small ({len(test)} < {steps}). Adjusting steps.")
            steps = len(test)

        ar_forecast = np.full(steps, np.nan)
        try:
            ar_model = AutoReg(train, lags=1).fit()
            ar_forecast = ar_model.forecast(steps=steps)
            print("AR Model Summary:")
            print(ar_model.summary())
        except Exception as e:
            print(f"Warning: AR model failed for {name}: {str(e)}")

        arma_forecast = np.full(steps, np.nan)
        try:
            arma_model = ARIMA(train, order=(1, 0, 1)).fit()
            arma_forecast = arma_model.forecast(steps=steps)
            print("ARMA Model Summary:")
            print(arma_model.summary())
        except Exception as e:
            print(f"Warning: ARMA model failed for {name}: {str(e)}")

        arima_forecast = np.full(steps, np.nan)
        try:
            arima_model = ARIMA(train, order=(1, 1, 1)).fit()
            arima_forecast = arima_model.forecast(steps=steps)
            print("ARIMA Model Summary:")
            print(arima_model.summary())
        except Exception as e:
            print(f"Warning: ARIMA model failed for {name}: {str(e)}")

        return train, test, ar_forecast, arma_forecast, arima_forecast, steps
    except Exception as e:
        print(f"Warning: Forecasting failed for {name}: {str(e)}")
        return None, None, np.full(steps, np.nan), np.full(steps, np.nan), np.full(steps, np.nan), steps

# Function to create a combined graph
def plot_combined_graph(apple_series, apple_diff, apple_is_diff, msft_series, msft_diff, msft_is_diff,
                       apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps,
                       msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps):
    try:
        fig, axes = plt.subplots(3, 2, figsize=(15, 12), sharex='col')
        fig.suptitle('Time Series Analysis: Apple and Microsoft Close Prices', fontsize=16)

        # Apple: Original and Differenced Series
        axes[0, 0].plot(apple_series, label='Original')
        if apple_is_diff:
            axes[0, 0].plot(apple_diff, label='Differenced', alpha=0.5)
        axes[0, 0].set_title('Apple Close: Stationarity')
        axes[0, 0].legend()

        # Microsoft: Original and Differenced Series
        axes[0, 1].plot(msft_series, label='Original')
        if msft_is_diff:
            axes[0, 1].plot(msft_diff, label='Differenced', alpha=0.5)
        axes[0, 1].set_title('Microsoft Close: Stationarity')
        axes[0, 1].legend()

        # Cointegration: Apple vs Microsoft
        axes[1, 0].plot(apple_series, label='Apple Close')
        axes[1, 0].plot(msft_series, label='Microsoft Close')
        axes[1, 0].set_title('Cointegration: Apple vs Microsoft')
        axes[1, 0].legend()

        # Empty subplot (for layout symmetry)
        axes[1, 1].axis('off')

        # Apple: Forecasts
        if apple_train is not None:
            axes[2, 0].plot(apple_train.index[-50:], apple_train[-50:], label='Train')
            axes[2, 0].plot(apple_test.index[:apple_steps], apple_test[:apple_steps], label='Test')
            axes[2, 0].plot(apple_test.index[:apple_steps], apple_ar, label='AR')
            axes[2, 0].plot(apple_test.index[:apple_steps], apple_arma, label='ARMA')
            axes[2, 0].plot(apple_test.index[:apple_steps], apple_arima, label='ARIMA')
            rolling_mean = apple_train.rolling(window=10).mean()
            axes[2, 0].plot(apple_train.index[-50:], rolling_mean[-50:], label='10-Period Mean', linestyle='--')
            axes[2, 0].set_title('Apple Close: Forecasts')
            axes[2, 0].legend()

        # Microsoft: Forecasts
        if msft_train is not None:
            axes[2, 1].plot(msft_train.index[-50:], msft_train[-50:], label='Train')
            axes[2, 1].plot(msft_test.index[:msft_steps], msft_test[:msft_steps], label='Test')
            axes[2, 1].plot(msft_test.index[:msft_steps], msft_ar, label='AR')
            axes[2, 1].plot(msft_test.index[:msft_steps], msft_arma, label='ARMA')
            axes[2, 1].plot(msft_test.index[:msft_steps], msft_arima, label='ARIMA')
            rolling_mean = msft_train.rolling(window=10).mean()
            axes[2, 1].plot(msft_train.index[-50:], rolling_mean[-50:], label='10-Period Mean', linestyle='--')
            axes[2, 1].set_title('Microsoft Close: Forecasts')
            axes[2, 1].legend()

        plt.tight_layout(rect=[0, 0, 1, 0.95])
        plt.savefig('combined_analysis.png')
        plt.close()
        print("Saved combined graph: combined_analysis.png")
    except Exception as e:
        print(f"Warning: Failed to create combined graph: {str(e)}")

# Function to plot individual forecasts
def plot_individual_forecasts(train, test, ar_forecast, arma_forecast, arima_forecast, name, steps=10):
    try:
        models = {'AR': ar_forecast, 'ARMA': arma_forecast, 'ARIMA': arima_forecast}
        for model_name, forecast in models.items():
            if len(forecast) != steps or np.isnan(forecast).all():
                print(f"Warning: Invalid {model_name} forecast for {name}. Skipping plot.")
                continue
            plt.figure(figsize=(12, 6))
            plt.plot(train.index[-50:], train[-50:], label='Train')
            plt.plot(test.index[:steps], test[:steps], label='Test')
            plt.plot(test.index[:steps], forecast, label=f'{model_name} Forecast')
            plt.title(f'{model_name} Forecasting for {name}')
            plt.legend()
            filename = f'{name}_{model_name}_forecast.png'
            plt.savefig(filename)
            plt.close()
            print(f"Saved plot: {filename}")
    except Exception as e:
        print(f"Warning: Failed to plot individual forecasts for {name}: {str(e)}")

# Main execution
def main():
    try:
        # Load data
        apple_df, msft_df = load_stock_data()
        apple_close = apple_df['Close']
        msft_close = msft_df['Close']

        # Ensure datetime indices
        apple_df, apple_close = ensure_datetime_index(apple_df, apple_close, "Apple Close")
        msft_df, msft_close = ensure_datetime_index(msft_df, msft_close, "Microsoft Close")

        # Stationarity tests
        apple_series, apple_is_diff = stationarity_tests(apple_close, "Apple Close")
        msft_series, msft_is_diff = stationarity_tests(msft_close, "Microsoft Close")

        # Cointegration test
        apple_series, msft_series = cointegration_test(apple_series, msft_series, "Apple Close", "Microsoft Close")

        # Fit models and forecast
        apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps = fit_and_forecast(apple_series, "Apple Close")
        msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps = fit_and_forecast(msft_series, "Microsoft Close")

        # Individual forecast plots
        if apple_train is not None:
            plot_individual_forecasts(apple_train, apple_test, apple_ar, apple_arma, apple_arima, "Apple Close", apple_steps)
        if msft_train is not None:
            plot_individual_forecasts(msft_train, msft_test, msft_ar, msft_arma, msft_arima, "Microsoft Close", msft_steps)

        # Combined graph
        plot_combined_graph(
            apple_close, apple_series if apple_is_diff else None, apple_is_diff,
            msft_close, msft_series if msft_is_diff else None, msft_is_diff,
            apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps,
            msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps
        )

        # List saved plots
        print("\nSaved Plots:")
        saved_files = [f for f in os.listdir() if f.endswith('.png')]
        for f in saved_files:
            print(f"- {f}")
        if not saved_files:
            print("No plots were saved.")
    except Exception as e:
        print(f"Error in main execution: {str(e)}")

if __name__ == "__main__":
    main()

import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, kpss, coint
import matplotlib.pyplot as plt
from google.colab import files
import warnings
import os

# Suppress specific statsmodels warnings
warnings.filterwarnings("ignore", category=UserWarning, message="Covariance matrix calculated using the outer product of gradients")

# Function to clean series (handle NaN/Inf)
def clean_series(series, name):
    try:
        print(f"Checking {name} for NaN/Inf values...")
        if not pd.api.types.is_numeric_dtype(series):
            raise ValueError(f"{name} contains non-numeric values.")
        if series.isna().any() or np.isinf(series).any():
            print(f"{name} contains NaN or Inf values. Cleaning...")
            series = series.fillna(method='ffill').fillna(method='bfill').dropna()
            series = series.replace([np.inf], series.max())
            series = series.replace([-np.inf], series.min())
        if series.isna().any():
            raise ValueError(f"{name} still contains NaN values after cleaning.")
        if len(series) == 0:
            raise ValueError(f"{name} is empty after cleaning.")
        print(f"{name} is clean with {len(series)} observations.")
        return series
    except Exception as e:
        raise ValueError(f"Failed to clean {name}: {str(e)}")

# Function to upload and read Excel files
def load_stock_data(max_retries=3):
    for attempt in range(max_retries):
        try:
            print("Upload APPLE 1 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Apple.")
            apple_filename = list(uploaded.keys())[0]
            if not apple_filename.endswith('.xlsx'):
                raise ValueError("Apple file must be an Excel (.xlsx) file.")
            apple_df = pd.read_excel(apple_filename)

            print("Upload MICROSOFT 1 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Microsoft.")
            msft_filename = list(uploaded.keys())[0]
            if not msft_filename.endswith('.xlsx'):
                raise ValueError("Microsoft file must be an Excel (.xlsx) file.")
            msft_df = pd.read_excel(msft_filename)

            if 'Close' not in apple_df.columns or 'Close' not in msft_df.columns:
                raise ValueError("Excel files must contain a 'Close' column.")

            apple_df['Close'] = clean_series(apple_df['Close'], "Apple Close")
            msft_df['Close'] = clean_series(msft_df['Close'], "Microsoft Close")

            return apple_df, msft_df
        except Exception as e:
            print(f"Error loading files (attempt {attempt + 1}/{max_retries}): {str(e)}")
            if attempt == max_retries - 1:
                raise ValueError("Failed to load Excel files after multiple attempts.")

# Function to ensure datetime index
def ensure_datetime_index(df, series, name):
    try:
        if not pd.api.types.is_datetime64_any_dtype(df.index):
            datetime_cols = ['Date', 'Timestamp', 'datetime', 'time']
            for col in datetime_cols:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors='coerce')
                    if df[col].isna().all():
                        raise ValueError(f"Invalid datetime values in {col} for {name}.")
                    df.set_index(col, inplace=True)
                    series.index = df.index
                    break
            else:
                print(f"Warning: No datetime column found for {name}. Using default index.")
                df.index = pd.RangeIndex(len(df))
                series.index = df.index
        return df, series
    except Exception as e:
        print(f"Warning: Failed to set datetime index for {name}: {str(e)}. Using default index.")
        df.index = pd.RangeIndex(len(df))
        series.index = df.index
        return df, series

# Function to perform stationarity tests and return differenced series
def stationarity_tests(series, name):
    try:
        print(f"\nStationarity Tests for {name}")
        series = clean_series(series, name)

        adf_result = adfuller(series, autolag='AIC')
        print(f"ADF Test p-value: {adf_result[1]:.4f}")
        kpss_result = kpss(series, regression='c')
        print(f"KPSS Test p-value: {kpss_result[1]:.4f}")

        plt.figure(figsize=(12, 6))
        plt.plot(series, label='Original Series')
        plt.title(f'Original {name} Series')
        plt.xlabel('Time')
        plt.ylabel('Price')
        plt.grid(True)
        plt.legend()
        plt.savefig(f'{name}_original_series.png')
        plt.close()

        is_differenced = False
        diff_series = series
        if adf_result[1] > 0.05 or kpss_result[1] < 0.05:
            print(f"{name} is non-stationary. Differencing...")
            diff_series = series.diff().dropna()
            diff_series = clean_series(diff_series, f"Differenced {name}")
            plt.figure(figsize=(12, 6))
            plt.plot(diff_series, label='Differenced Series')
            plt.title(f'Differenced {name} Series')
            plt.xlabel('Time')
            plt.ylabel('Price Difference')
            plt.grid(True)
            plt.legend()
            plt.savefig(f'{name}_differenced_series.png')
            plt.close()
            is_differenced = True
        return diff_series, is_differenced
    except Exception as e:
        print(f"Warning: Stationarity tests failed for {name}: {str(e)}. Using original series.")
        return series, False

# Function to perform cointegration test
def cointegration_test(series1, series2, name1, name2):
    try:
        print(f"\nCointegration Test between {name1} and {name2}")
        df = pd.DataFrame({name1: series1, name2: series2}).dropna()
        series1, series2 = df[name1], df[name2]
        if len(series1) < 2:
            raise ValueError("Insufficient data for cointegration test.")

        series1 = clean_series(series1, name1)
        series2 = clean_series(series2, name2)

        score, p_value, _ = coint(series1, series2)
        print(f"Engle-Granger Cointegration Test p-value: {p_value:.4f}")
        if p_value < 0.05:
            print("Series are cointegrated")
        else:
            print("Series are not cointegrated")

        plt.figure(figsize=(12, 6))
        plt.plot(series1, label=name1)
        plt.plot(series2, label=name2)
        plt.title(f'{name1} vs {name2} for Cointegration')
        plt.xlabel('Time')
        plt.ylabel('Price')
        plt.grid(True)
        plt.legend()
        plt.savefig(f'{name1}_vs_{name2}_cointegration.png')
        plt.close()

        return series1, series2
    except Exception as e:
        print(f"Warning: Cointegration test failed: {str(e)}. Skipping.")
        return series1, series2

# Function to fit and forecast models
def fit_and_forecast(series, name, steps=10):
    try:
        print(f"\nFitting Models for {name}")
        series = clean_series(series.dropna(), name)
        if len(series) < 50:
            raise ValueError(f"Insufficient data for {name}: {len(series)} observations.")

        train_size = int(len(series) * 0.8)
        train, test = series[:train_size], series[train_size:]
        if len(test) < steps:
            print(f"Warning: Test set too small ({len(test)} < {steps}). Adjusting steps.")
            steps = len(test)

        ar_forecast = np.full(steps, np.nan)
        try:
            ar_model = AutoReg(train, lags=1).fit()
            ar_forecast = ar_model.forecast(steps=steps)
            print("AR Model Summary:")
            print(ar_model.summary())
        except Exception as e:
            print(f"Warning: AR model failed for {name}: {str(e)}")

        arma_forecast = np.full(steps, np.nan)
        try:
            arma_model = ARIMA(train, order=(1, 0, 1)).fit()
            arma_forecast = arma_model.forecast(steps=steps)
            print("ARMA Model Summary:")
            print(arma_model.summary())
        except Exception as e:
            print(f"Warning: ARMA model failed for {name}: {str(e)}")

        arima_forecast = np.full(steps, np.nan)
        try:
            arima_model = ARIMA(train, order=(1, 1, 1)).fit()
            arima_forecast = arima_model.forecast(steps=steps)
            print("ARIMA Model Summary:")
            print(arima_model.summary())
        except Exception as e:
            print(f"Warning: ARIMA model failed for {name}: {str(e)}")

        return train, test, ar_forecast, arma_forecast, arima_forecast, steps
    except Exception as e:
        print(f"Warning: Forecasting failed for {name}: {str(e)}")
        return None, None, np.full(steps, np.nan), np.full(steps, np.nan), np.full(steps, np.nan), steps

# Function to create an enhanced combined graph
def plot_combined_graph(apple_series, apple_diff, apple_is_diff, msft_series, msft_diff, msft_is_diff,
                       apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps,
                       msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps):
    try:
        fig, axes = plt.subplots(3, 2, figsize=(18, 12), gridspec_kw={'height_ratios': [1, 1, 1.5]})
        fig.suptitle('Time Series Analysis: Apple and Microsoft Close Prices', fontsize=16, y=1.02)

        # Apple: Original and Differenced Series
        axes[0, 0].plot(apple_series, label='Original', color='blue')
        if apple_is_diff:
            axes[0, 0].plot(apple_diff, label='Differenced', color='orange', alpha=0.5)
        axes[0, 0].set_title('Apple Close: Stationarity')
        axes[0, 0].set_xlabel('Time')
        axes[0, 0].set_ylabel('Price / Diff')
        axes[0, 0].grid(True)
        axes[0, 0].legend()

        # Microsoft: Original and Differenced Series
        axes[0, 1].plot(msft_series, label='Original', color='blue')
        if msft_is_diff:
            axes[0, 1].plot(msft_diff, label='Differenced', color='orange', alpha=0.5)
        axes[0, 1].set_title('Microsoft Close: Stationarity')
        axes[0, 1].set_xlabel('Time')
        axes[0, 1].set_ylabel('Price / Diff')
        axes[0, 1].grid(True)
        axes[0, 1].legend()

        # Cointegration: Normalized Apple vs Microsoft
        if len(apple_series) > 0 and len(msft_series) > 0:
            apple_norm = (apple_series - apple_series.mean()) / apple_series.std()
            msft_norm = (msft_series - msft_series.mean()) / msft_series.std()
            axes[1, 0].plot(apple_norm, label='Apple Close (Normalized)', color='blue')
            axes[1, 0].plot(msft_norm, label='Microsoft Close (Normalized)', color='green')
            axes[1, 0].set_title('Cointegration: Normalized Apple vs Microsoft')
            axes[1, 0].set_xlabel('Time')
            axes[1, 0].set_ylabel('Normalized Price')
            axes[1, 0].grid(True)
            axes[1, 0].legend()

        # Empty subplot
        axes[1, 1].axis('off')

        # Apple: Forecasts
        if apple_train is not None and len(apple_train) > 0:
            axes[2, 0].plot(apple_train.index[-50:], apple_train[-50:], label='Train', color='blue')
            axes[2, 0].plot(apple_test.index[:apple_steps], apple_test[:apple_steps], label='Test', color='black')
            if not np.isnan(apple_ar).all():
                axes[2, 0].plot(apple_test.index[:apple_steps], apple_ar, label='AR', color='red')
            if not np.isnan(apple_arma).all():
                axes[2, 0].plot(apple_test.index[:apple_steps], apple_arma, label='ARMA', color='green')
            if not np.isnan(apple_arima).all():
                axes[2, 0].plot(apple_test.index[:apple_steps], apple_arima, label='ARIMA', color='purple')
            rolling_mean = apple_train.rolling(window=10).mean()
            axes[2, 0].plot(apple_train.index[-50:], rolling_mean[-50:], label='10-Period Mean', color='orange', linestyle='--')
            axes[2, 0].set_title('Apple Close: Forecasts')
            axes[2, 0].set_xlabel('Time')
            axes[2, 0].set_ylabel('Price')
            axes[2, 0].grid(True)
            axes[2, 0].legend()

        # Microsoft: Forecasts
        if msft_train is not None and len(msft_train) > 0:
            axes[2, 1].plot(msft_train.index[-50:], msft_train[-50:], label='Train', color='blue')
            axes[2, 1].plot(msft_test.index[:msft_steps], msft_test[:msft_steps], label='Test', color='black')
            if not np.isnan(msft_ar).all():
                axes[2, 1].plot(msft_test.index[:msft_steps], msft_ar, label='AR', color='red')
            if not np.isnan(msft_arma).all():
                axes[2, 1].plot(msft_test.index[:msft_steps], msft_arma, label='ARMA', color='green')
            if not np.isnan(msft_arima).all():
                axes[2, 1].plot(msft_test.index[:msft_steps], msft_arima, label='ARIMA', color='purple')
            rolling_mean = msft_train.rolling(window=10).mean()
            axes[2, 1].plot(msft_train.index[-50:], rolling_mean[-50:], label='10-Period Mean', color='orange', linestyle='--')
            axes[2, 1].set_title('Microsoft Close: Forecasts')
            axes[2, 1].set_xlabel('Time')
            axes[2, 1].set_ylabel('Price')
            axes[2, 1].grid(True)
            axes[2, 1].legend()

        plt.tight_layout(rect=[0, 0, 1, 0.95])
        plt.savefig('combined_analysis.png', dpi=300, bbox_inches='tight')
        plt.close()
        print("Saved enhanced combined graph: combined_analysis.png")
    except Exception as e:
        print(f"Warning: Failed to create combined graph: {str(e)}")

# Function to plot individual forecasts
def plot_individual_forecasts(train, test, ar_forecast, arma_forecast, arima_forecast, name, steps=10):
    try:
        models = {'AR': ar_forecast, 'ARMA': arma_forecast, 'ARIMA': arima_forecast}
        for model_name, forecast in models.items():
            if len(forecast) != steps or np.isnan(forecast).all():
                print(f"Warning: Invalid {model_name} forecast for {name}. Skipping plot.")
                continue
            plt.figure(figsize=(12, 6))
            plt.plot(train.index[-50:], train[-50:], label='Train', color='blue')
            plt.plot(test.index[:steps], test[:steps], label='Test', color='black')
            plt.plot(test.index[:steps], forecast, label=f'{model_name} Forecast', color='red')
            plt.title(f'{model_name} Forecasting for {name}')
            plt.xlabel('Time')
            plt.ylabel('Price')
            plt.grid(True)
            plt.legend()
            filename = f'{name}_{model_name}_forecast.png'
            plt.savefig(filename)
            plt.close()
            print(f"Saved plot: {filename}")
    except Exception as e:
        print(f"Warning: Failed to plot individual forecasts for {name}: {str(e)}")

# Main execution
def main():
    try:
        # Load data
        apple_df, msft_df = load_stock_data()
        apple_close = apple_df['Close']
        msft_close = msft_df['Close']

        # Ensure datetime indices
        apple_df, apple_close = ensure_datetime_index(apple_df, apple_close, "Apple Close")
        msft_df, msft_close = ensure_datetime_index(msft_df, msft_close, "Microsoft Close")

        # Stationarity tests
        apple_series, apple_is_diff = stationarity_tests(apple_close, "Apple Close")
        msft_series, msft_is_diff = stationarity_tests(msft_close, "Microsoft Close")

        # Cointegration test
        apple_series, msft_series = cointegration_test(apple_series, msft_series, "Apple Close", "Microsoft Close")

        # Fit models and forecast
        apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps = fit_and_forecast(apple_series, "Apple Close")
        msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps = fit_and_forecast(msft_series, "Microsoft Close")

        # Individual forecast plots
        if apple_train is not None:
            plot_individual_forecasts(apple_train, apple_test, apple_ar, apple_arma, apple_arima, "Apple Close", apple_steps)
        if msft_train is not None:
            plot_individual_forecasts(msft_train, msft_test, msft_ar, msft_arma, msft_arima, "Microsoft Close", msft_steps)

        # Combined graph
        plot_combined_graph(
            apple_close, apple_series if apple_is_diff else None, apple_is_diff,
            msft_close, msft_series if msft_is_diff else None, msft_is_diff,
            apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps,
            msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps
        )

        # List saved plots
        print("\nSaved Plots:")
        saved_files = [f for f in os.listdir() if f.endswith('.png')]
        for f in saved_files:
            print(f"- {f}")
        if not saved_files:
            print("No plots were saved.")
    except Exception as e:
        print(f"Error in main execution: {str(e)}")

if __name__ == "__main__":
    main()

import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, kpss, coint
import matplotlib.pyplot as plt
from google.colab import files
import warnings
import os
import IPython.display as display

# Suppress statsmodels warnings
warnings.filterwarnings("ignore", category=UserWarning, message="Covariance matrix calculated using the outer product of gradients")

# Function to clean series (handle NaN/Inf)
def clean_series(series, name):
    try:
        print(f"Checking {name} for NaN/Inf values...")
        if not pd.api.types.is_numeric_dtype(series):
            raise ValueError(f"{name} contains non-numeric values.")
        if series.isna().any() or np.isinf(series).any():
            print(f"{name} contains NaN or Inf values. Cleaning...")
            series = series.fillna(method='ffill').fillna(method='bfill').dropna()
            series = series.replace([np.inf], series.max())
            series = series.replace([-np.inf], series.min())
        if series.isna().any():
            raise ValueError(f"{name} still contains NaN values after cleaning.")
        if len(series) == 0:
            raise ValueError(f"{name} is empty after cleaning.")
        print(f"{name} is clean with {len(series)} observations.")
        return series
    except Exception as e:
        raise ValueError(f"Failed to clean {name}: {str(e)}")

# Function to upload and read Excel files
def load_stock_data(max_retries=3):
    for attempt in range(max_retries):
        try:
            print("Upload APPLE 1 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Apple.")
            apple_filename = list(uploaded.keys())[0]
            if not apple_filename.endswith('.xlsx'):
                raise ValueError("Apple file must be an Excel (.xlsx) file.")
            apple_df = pd.read_excel(apple_filename)

            print("Upload MICROSOFT 1 MIN.xlsx")
            uploaded = files.upload()
            if not uploaded:
                raise ValueError("No file uploaded for Microsoft.")
            msft_filename = list(uploaded.keys())[0]
            if not msft_filename.endswith('.xlsx'):
                raise ValueError("Microsoft file must be an Excel (.xlsx) file.")
            msft_df = pd.read_excel(msft_filename)

            if 'Close' not in apple_df.columns or 'Close' not in msft_df.columns:
                raise ValueError("Excel files must contain a 'Close' column.")

            apple_df['Close'] = clean_series(apple_df['Close'], "Apple Close")
            msft_df['Close'] = clean_series(msft_df['Close'], "Microsoft Close")

            print(f"Apple data shape: {apple_df.shape}, Microsoft data shape: {msft_df.shape}")
            return apple_df, msft_df
        except Exception as e:
            print(f"Error loading files (attempt {attempt + 1}/{max_retries}): {str(e)}")
            if attempt == max_retries - 1:
                raise ValueError("Failed to load Excel files after multiple attempts.")

# Function to ensure datetime index
def ensure_datetime_index(df, series, name):
    try:
        if not pd.api.types.is_datetime64_any_dtype(df.index):
            datetime_cols = ['Date', 'Timestamp', 'datetime', 'time']
            for col in datetime_cols:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors='coerce')
                    if df[col].isna().all():
                        raise ValueError(f"Invalid datetime values in {col} for {name}.")
                    df.set_index(col, inplace=True)
                    series.index = df.index
                    break
            else:
                print(f"Warning: No datetime column found for {name}. Using default index.")
                df.index = pd.RangeIndex(len(df))
                series.index = df.index
        return df, series
    except Exception as e:
        print(f"Warning: Failed to set datetime index for {name}: {str(e)}. Using default index.")
        df.index = pd.RangeIndex(len(df))
        series.index = df.index
        return df, series

# Function to perform stationarity tests
def stationarity_tests(series, name):
    try:
        print(f"\nStationarity Tests for {name}")
        series = clean_series(series, name)

        adf_result = adfuller(series, autolag='AIC')
        print(f"ADF Test p-value: {adf_result[1]:.4f}")
        kpss_result = kpss(series, regression='c')
        print(f"KPSS Test p-value: {kpss_result[1]:.4f}")

        plt.figure(figsize=(12, 6))
        plt.plot(series, label='Original Series', color='blue')
        plt.title(f'Original {name} Series')
        plt.xlabel('Time')
        plt.ylabel('Price')
        plt.grid(True)
        plt.legend()
        filename = f'{name}_original_series.png'
        plt.savefig(filename)
        plt.show()
        plt.close()
        print(f"Saved and displayed plot: {filename}")

        is_differenced = False
        diff_series = series
        if adf_result[1] > 0.05 or kpss_result[1] < 0.05:
            print(f"{name} is non-stationary. Differencing...")
            diff_series = series.diff().dropna()
            diff_series = clean_series(diff_series, f"Differenced {name}")
            plt.figure(figsize=(12, 6))
            plt.plot(diff_series, label='Differenced Series', color='orange')
            plt.title(f'Differenced {name} Series')
            plt.xlabel('Time')
            plt.ylabel('Price Difference')
            plt.grid(True)
            plt.legend()
            filename = f'{name}_differenced_series.png'
            plt.savefig(filename)
            plt.show()
            plt.close()
            print(f"Saved and displayed plot: {filename}")
            is_differenced = True
        return diff_series, is_differenced
    except Exception as e:
        print(f"Warning: Stationarity tests failed for {name}: {str(e)}. Using original series.")
        return series, False

# Function to perform cointegration test
def cointegration_test(series1, series2, name1, name2):
    try:
        print(f"\nCointegration Test between {name1} and {name2}")
        df = pd.DataFrame({name1: series1, name2: series2}).dropna()
        series1, series2 = df[name1], df[name2]
        if len(series1) < 2:
            raise ValueError("Insufficient data for cointegration test.")

        series1 = clean_series(series1, name1)
        series2 = clean_series(series2, name2)

        score, p_value, _ = coint(series1, series2)
        print(f"Engle-Granger Cointegration Test p-value: {p_value:.4f}")
        if p_value < 0.05:
            print("Series are cointegrated")
        else:
            print("Series are not cointegrated")

        plt.figure(figsize=(12, 6))
        plt.plot(series1, label=name1, color='blue')
        plt.plot(series2, label=name2, color='green')
        plt.title(f'{name1} vs {name2} for Cointegration')
        plt.xlabel('Time')
        plt.ylabel('Price')
        plt.grid(True)
        plt.legend()
        filename = f'{name1}_vs_{name2}_cointegration.png'
        plt.savefig(filename)
        plt.show()
        plt.close()
        print(f"Saved and displayed plot: {filename}")

        return series1, series2
    except Exception as e:
        print(f"Warning: Cointegration test failed: {str(e)}. Skipping.")
        return series1, series2

# Function to fit and forecast models
def fit_and_forecast(series, name, steps=10):
    try:
        print(f"\nFitting Models for {name}")
        series = clean_series(series.dropna(), name)
        if len(series) < 50:
            raise ValueError(f"Insufficient data for {name}: {len(series)} observations.")

        train_size = int(len(series) * 0.8)
        train, test = series[:train_size], series[train_size:]
        if len(test) < steps:
            print(f"Warning: Test set too small ({len(test)} < {steps}). Adjusting steps.")
            steps = len(test)

        ar_forecast = np.full(steps, np.nan)
        try:
            ar_model = AutoReg(train, lags=1).fit()
            ar_forecast = ar_model.forecast(steps=steps)
            print("AR Model Summary:")
            print(ar_model.summary())
        except Exception as e:
            print(f"Warning: AR model failed for {name}: {str(e)}")

        arma_forecast = np.full(steps, np.nan)
        try:
            arma_model = ARIMA(train, order=(1, 0, 1)).fit()
            arma_forecast = arma_model.forecast(steps=steps)
            print("ARMA Model Summary:")
            print(arma_model.summary())
        except Exception as e:
            print(f"Warning: ARMA model failed for {name}: {str(e)}")

        arima_forecast = np.full(steps, np.nan)
        try:
            arima_model = ARIMA(train, order=(1, 1, 1)).fit()
            arima_forecast = arima_model.forecast(steps=steps)
            print("ARIMA Model Summary:")
            print(arima_model.summary())
        except Exception as e:
            print(f"Warning: ARIMA model failed for {name}: {str(e)}")

        return train, test, ar_forecast, arma_forecast, arima_forecast, steps
    except Exception as e:
        print(f"Warning: Forecasting failed for {name}: {str(e)}")
        return None, None, np.full(steps, np.nan), np.full(steps, np.nan), np.full(steps, np.nan), steps

# Function to create combined graph
def plot_combined_graph(apple_series, apple_diff, apple_is_diff, msft_series, msft_diff, msft_is_diff,
                       apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps,
                       msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps):
    try:
        print("Generating combined graph...")
        fig, axes = plt.subplots(3, 2, figsize=(18, 12), gridspec_kw={'height_ratios': [1, 1, 1.5]})
        fig.suptitle('Time Series Analysis: Apple and Microsoft Close Prices', fontsize=16, y=1.02)

        # Apple: Original and Differenced Series
        if len(apple_series) > 0:
            axes[0, 0].plot(apple_series, label='Original', color='blue')
            if apple_is_diff and len(apple_diff) > 0:
                axes[0, 0].plot(apple_diff, label='Differenced', color='orange', alpha=0.5)
            axes[0, 0].set_title('Apple Close: Stationarity')
            axes[0, 0].set_xlabel('Time')
            axes[0, 0].set_ylabel('Price / Diff')
            axes[0, 0].grid(True)
            axes[0, 0].legend()
        else:
            axes[0, 0].text(0.5, 0.5, 'No Apple data', ha='center', va='center')

        # Microsoft: Original and Differenced Series
        if len(msft_series) > 0:
            axes[0, 1].plot(msft_series, label='Original', color='blue')
            if msft_is_diff and len(msft_diff) > 0:
                axes[0, 1].plot(msft_diff, label='Differenced', color='orange', alpha=0.5)
            axes[0, 1].set_title('Microsoft Close: Stationarity')
            axes[0, 1].set_xlabel('Time')
            axes[0, 1].set_ylabel('Price / Diff')
            axes[0, 1].grid(True)
            axes[0, 1].legend()
        else:
            axes[0, 1].text(0.5, 0.5, 'No Microsoft data', ha='center', va='center')

        # Cointegration: Normalized Apple vs Microsoft
        if len(apple_series) > 0 and len(msft_series) > 0:
            apple_norm = (apple_series - apple_series.mean()) / apple_series.std()
            msft_norm = (msft_series - msft_series.mean()) / msft_series.std()
            axes[1, 0].plot(apple_norm, label='Apple Close (Normalized)', color='blue')
            axes[1, 0].plot(msft_norm, label='Microsoft Close (Normalized)', color='green')
            axes[1, 0].set_title('Cointegration: Normalized Apple vs Microsoft')
            axes[1, 0].set_xlabel('Time')
            axes[1, 0].set_ylabel('Normalized Price')
            axes[1, 0].grid(True)
            axes[1, 0].legend()
        else:
            axes[1, 0].text(0.5, 0.5, 'No data for cointegration', ha='center', va='center')

        # Empty subplot
        axes[1, 1].axis('off')

        # Apple: Forecasts
        if apple_train is not None and len(apple_train) > 0:
            axes[2, 0].plot(apple_train.index[-50:], apple_train[-50:], label='Train', color='blue')
            axes[2, 0].plot(apple_test.index[:apple_steps], apple_test[:apple_steps], label='Test', color='black')
            if not np.isnan(apple_ar).all():
                axes[2, 0].plot(apple_test.index[:apple_steps], apple_ar, label='AR', color='red')
            if not np.isnan(apple_arma).all():
                axes[2, 0].plot(apple_test.index[:apple_steps], apple_arma, label='ARMA', color='green')
            if not np.isnan(apple_arima).all():
                axes[2, 0].plot(apple_test.index[:apple_steps], apple_arima, label='ARIMA', color='purple')
            rolling_mean = apple_train.rolling(window=10).mean()
            axes[2, 0].plot(apple_train.index[-50:], rolling_mean[-50:], label='10-Period Mean', color='orange', linestyle='--')
            axes[2, 0].set_title('Apple Close: Forecasts')
            axes[2, 0].set_xlabel('Time')
            axes[2, 0].set_ylabel('Price')
            axes[2, 0].grid(True)
            axes[2, 0].legend()
        else:
            axes[2, 0].text(0.5, 0.5, 'No Apple forecast data', ha='center', va='center')

        # Microsoft: Forecasts
        if msft_train is not None and len(msft_train) > 0:
            axes[2, 1].plot(msft_train.index[-50:], msft_train[-50:], label='Train', color='blue')
            axes[2, 1].plot(msft_test.index[:msft_steps], msft_test[:msft_steps], label='Test', color='black')
            if not np.isnan(msft_ar).all():
                axes[2, 1].plot(msft_test.index[:msft_steps], msft_ar, label='AR', color='red')
            if not np.isnan(msft_arma).all():
                axes[2, 1].plot(msft_test.index[:msft_steps], msft_arma, label='ARMA', color='green')
            if not np.isnan(msft_arima).all():
                axes[2, 1].plot(msft_test.index[:msft_steps], msft_arima, label='ARIMA', color='purple')
            rolling_mean = msft_train.rolling(window=10).mean()
            axes[2, 1].plot(msft_train.index[-50:], rolling_mean[-50:], label='10-Period Mean', color='orange', linestyle='--')
            axes[2, 1].set_title('Microsoft Close: Forecasts')
            axes[2, 1].set_xlabel('Time')
            axes[2, 1].set_ylabel('Price')
            axes[2, 1].grid(True)
            axes[2, 1].legend()
        else:
            axes[2, 1].text(0.5, 0.5, 'No Microsoft forecast data', ha='center', va='center')

        plt.tight_layout(rect=[0, 0, 1, 0.95])
        filename = 'combined_analysis.png'
        plt.savefig(filename, dpi=300, bbox_inches='tight')
        plt.show()
        plt.close()
        print(f"Saved and displayed combined graph: {filename}")
        # Force display of saved file
        display.display(display.Image(filename))
    except Exception as e:
        print(f"Warning: Failed to create combined graph: {str(e)}")

# Function to plot individual forecasts
def plot_individual_forecasts(train, test, ar_forecast, arma_forecast, arima_forecast, name, steps=10):
    try:
        models = {'AR': ar_forecast, 'ARMA': arma_forecast, 'ARIMA': arima_forecast}
        for model_name, forecast in models.items():
            if len(forecast) != steps or np.isnan(forecast).all():
                print(f"Warning: Invalid {model_name} forecast for {name}. Skipping plot.")
                continue
            plt.figure(figsize=(12, 6))
            plt.plot(train.index[-50:], train[-50:], label='Train', color='blue')
            plt.plot(test.index[:steps], test[:steps], label='Test', color='black')
            plt.plot(test.index[:steps], forecast, label=f'{model_name} Forecast', color='red')
            plt.title(f'{model_name} Forecasting for {name}')
            plt.xlabel('Time')
            plt.ylabel('Price')
            plt.grid(True)
            plt.legend()
            filename = f'{name}_{model_name}_forecast.png'
            plt.savefig(filename)
            plt.show()
            plt.close()
            print(f"Saved and displayed plot: {filename}")
            display.display(display.Image(filename))
    except Exception as e:
        print(f"Warning: Failed to plot individual forecasts for {name}: {str(e)}")

# Main execution
def main():
    try:
        # Load data
        apple_df, msft_df = load_stock_data()
        apple_close = apple_df['Close']
        msft_close = msft_df['Close']

        # Ensure datetime indices
        apple_df, apple_close = ensure_datetime_index(apple_df, apple_close, "Apple Close")
        msft_df, msft_close = ensure_datetime_index(msft_df, msft_close, "Microsoft Close")

        # Stationarity tests
        apple_series, apple_is_diff = stationarity_tests(apple_close, "Apple Close")
        msft_series, msft_is_diff = stationarity_tests(msft_close, "Microsoft Close")

        # Cointegration test
        apple_series, msft_series = cointegration_test(apple_series, msft_series, "Apple Close", "Microsoft Close")

        # Fit models and forecast
        apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps = fit_and_forecast(apple_series, "Apple Close")
        msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps = fit_and_forecast(msft_series, "Microsoft Close")

        # Individual forecast plots
        if apple_train is not None and len(apple_train) > 0:
            plot_individual_forecasts(apple_train, apple_test, apple_ar, apple_arma, apple_arima, "Apple Close", apple_steps)
        if msft_train is not None and len(msft_train) > 0:
            plot_individual_forecasts(msft_train, msft_test, msft_ar, msft_arma, msft_arima, "Microsoft Close", msft_steps)

        # Combined graph
        if len(apple_series) > 0 or len(msft_series) > 0:
            plot_combined_graph(
                apple_close, apple_series if apple_is_diff else None, apple_is_diff,
                msft_close, msft_series if msft_is_diff else None, msft_is_diff,
                apple_train, apple_test, apple_ar, apple_arma, apple_arima, apple_steps,
                msft_train, msft_test, msft_ar, msft_arma, msft_arima, msft_steps
            )

        # List and download saved plots
        print("\nSaved Plots:")
        saved_files = [f for f in os.listdir() if f.endswith('.png')]
        for f in saved_files:
            print(f"- {f}")
            files.download(f)
        if not saved_files:
            print("No plots were saved.")
    except Exception as e:
        print(f"Error in main execution: {str(e)}")

if __name__ == "__main__":
    main()